### ISSUE TITLE
希望能提供基于spring boot environment 的测试服务直连选项

### ISSUE THREAD

**Issue by chpengzh** [alipay/sofa-rpc-boot-projects#109]
### Your question

目前 SOFA-RPC 提供了[基于注解的直连参数](http://www.sofastack.tech/sofa-rpc/docs/Peer-To-Peer)配置方式 ，但是这种方式对于 artifact jar 来说不太友好，需要重新构建才能测试。 我认为 spring boot 的环境变量策略就是一个比较好的方法。

由于SOFA的服务是以接口类为单位的，希望能有类似于`logging.level`一样的配置方法，以 `application.yaml` 为例:

```yaml
com.alipay.sofa.rpc:
    ref:
        com.some.clazz.DemoService: bolt://127.0.0.1:9999
        com.some.pkg: bolt://127.0.0.1:10000
```

这样针对不同的包服务或者特定的类服务，就能简单的指定直连测试的地址。

对已经生成的 artifact jar 而言，也可以简单的通过修改启动参数的方式进行直连测试

```
java -jar my-demo-app.jar \
    --com.alipay.sofa.rpc.ref.com.some.pkg=bolt://10.1.34.68:12200 \
    --com.alipay.sofa.rpc.ref.com.some.clazz.DemoService=bolt://10.1.34.68:12201
```

还有 `com.alipay.sofa` 感觉有点长，yaml里面用着怪怪的，改短点有商量么?

### Environment

- Starter version:                                 new feature
- JVM version (e.g. `java -version`): 1.8+
- OS version (e.g. `uname -a`):         any
- Maven version:                                 3.2.0+
- IDE version:                                       idea/eclipse
